name: rubiks_cube_solver
description: A Flutter mini-app for solving 3x3 Rubik's cube
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  cuber: ^0.4.0
  flutter_scene: ^0.9.2-0
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21  # Android min sdk min:16, default 21
  adaptive_icon_background: "#121212"  # Background color for Android adaptive icon
  adaptive_icon_foreground: "assets/icon/icon.png"  # Foreground image for Android adaptive icon
  remove_alpha_ios: true  # Remove alpha channel for iOS (App Store requirement)

